spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.cc.ssm.user.entity,com.cc.ssm.person.entity
  mapper-locations: classpath*:com/cc/ssm/user/dao/*.xml,classpath*:com/cc/ssm/person/mapper/xml/*.xml

#编码格式
#spring.http.encoding.force: true
#spring.http.encoding.charset: UTF-8
#spring.http.encoding.enabled: true
#server.tomcat.uri-encoding: UTF-8


